mod artifact_uploader;
pub mod capabilities;
mod config;
mod credentials;
mod pin_manager;
mod probe;
mod task_runner;
mod tls_pinning;
mod ws_client;

use std::collections::HashMap;
use std::sync::Mutex;
use tauri::{AppHandle, Emitter, Manager, State};
use tokio::sync::{oneshot, watch};

struct AppState {
    ws_stop_tx: Option<watch::Sender<bool>>,
}

/// Pending user-approval requests. The ws_client inserts a oneshot sender here,
/// emits a `permission_request` event, then awaits the receiver. The frontend
/// calls `approve_action` or `deny_action` to complete the oneshot.
pub struct ApprovalState {
    pub pending: HashMap<String, oneshot::Sender<bool>>,
}

#[derive(serde::Serialize)]
struct AgentStatus {
    paired: bool,
    relay_url: String,
    hostname: String,
    agent_machine_id: String,
}

// ── Tauri command return types ────────────────────────────────────────────────

#[derive(serde::Serialize)]
struct RelayDefaults {
    relay_url: String,
}

/// Result returned to the frontend after successful pairing so the UI can
/// immediately render the QR code without a second round-trip.
#[derive(serde::Serialize)]
struct PairResult {
    paired: bool,
    relay_url: String,
    hostname: String,
    agent_machine_id: String,
    link_token: String,
    link_code: String,
}

/// Short-lived phone link returned by get_phone_link / after pairing.
/// The frontend encodes { relayUrl, linkToken } as a QR code for the phone.
#[derive(serde::Serialize)]
struct PhoneLinkResult {
    relay_url: String,
    link_token: String,
    link_code: String,
}

// ── Constants ─────────────────────────────────────────────────────────────────

// RELAY_URL is a public endpoint address, not a secret.
const RELAY_URL: &str = env!("VITE_RELAY_URL");

// VITE_BOOTSTRAP_TOKEN is intentionally absent — see build.rs.

// ── Tauri commands ────────────────────────────────────────────────────────────

#[tauri::command]
fn get_status(app: AppHandle, state: State<Mutex<AppState>>) -> AgentStatus {
    let _ = state;
    let cfg = config::load(&app);
    let has_token = credentials::load_token().ok().flatten().is_some();
    AgentStatus {
        paired: cfg.is_paired() && has_token,
        relay_url: cfg.relay_url,
        hostname: cfg.hostname,
        agent_machine_id: cfg.agent_machine_id,
    }
}

#[tauri::command]
fn get_relay_defaults(app: AppHandle) -> RelayDefaults {
    let cfg = config::load(&app);
    let relay_url = if !cfg.relay_url_override.is_empty() {
        cfg.relay_url_override.clone()
    } else {
        RELAY_URL.trim_end_matches('/').to_string()
    };
    RelayDefaults { relay_url }
}

#[tauri::command]
fn update_relay_url(app: AppHandle, url: String) -> Result<(), String> {
    let url = url.trim().trim_end_matches('/').to_string();
    validate_relay_url(&url)?;
    let mut cfg = config::load(&app);
    // Clear stored pins so TOFU runs against the new relay's certificate.
    if cfg.relay_url_override != url {
        pin_manager::clear_pins();
    }
    cfg.relay_url_override = url;
    config::save(&app, &cfg)
}

/// Pair this machine by claiming a one-time code generated by the phone app.
/// No embedded secret is required — the code itself is the authorization.
#[tauri::command]
async fn pair_with_code(
    app: AppHandle,
    state: State<'_, Mutex<AppState>>,
    code: String,
) -> Result<PairResult, String> {
    validate_pairing_code(code.trim())?;

    let cfg = config::load(&app);
    let relay_url = if !cfg.relay_url_override.is_empty() {
        cfg.relay_url_override.trim_end_matches('/').to_string()
    } else {
        RELAY_URL.trim_end_matches('/').to_string()
    };
    let hostname = config::get_hostname();
    let os = std::env::consts::OS.to_string();

    let claim_url = format!("{relay_url}/agent/pair/{}/claim", code.trim());
    let client = tls_pinning::get_pinned_http_client();
    let resp = client
        .post(&claim_url)
        .json(&serde_json::json!({ "hostname": hostname, "os": os }))
        .send()
        .await
        .map_err(|e| format!("Network error: {e}"))?;

    if !resp.status().is_success() {
        let status = resp.status();
        let body = resp.text().await.unwrap_or_default();
        let msg = serde_json::from_str::<serde_json::Value>(&body)
            .ok()
            .and_then(|v| v["error"].as_str().map(str::to_string))
            .unwrap_or_else(|| format!("Error {status}"));
        return Err(msg);
    }

    let body: serde_json::Value = resp.json().await.map_err(|e| e.to_string())?;
    let token = body["token"].as_str().ok_or("No token in response")?.to_string();
    let agent_machine_id = body["agentMachineId"].as_str().ok_or("No agentMachineId")?.to_string();

    credentials::store_token(&token).map_err(|e| format!("Failed to store token: {e}"))?;
    if let Some(rt) = body["refreshToken"].as_str() {
        let _ = credentials::store_refresh_token(rt);
    }

    let existing = config::load(&app);
    let new_cfg = config::AgentConfig {
        relay_url: relay_url.clone(),
        token: String::new(),
        agent_machine_id: agent_machine_id.clone(),
        hostname: hostname.clone(),
        relay_url_override: existing.relay_url_override,
        token_issued_at: Some(now_unix()),
    };
    config::save(&app, &new_cfg).map_err(|e| format!("Failed to save config: {e}"))?;
    start_ws_connection(&app, &state, relay_url.clone(), token.clone());

    // Immediately generate a phone link so the frontend can render a QR.
    let link = fetch_phone_link(&relay_url, &token).await;
    Ok(PairResult {
        paired: true,
        relay_url,
        hostname,
        agent_machine_id,
        link_token: link.as_ref().map(|l| l.link_token.clone()).unwrap_or_default(),
        link_code: link.as_ref().map(|l| l.link_code.clone()).unwrap_or_default(),
    })
}

/// Also keep the original `pair` command for relay-URL-explicit pairing (deep link / CLI).
#[tauri::command]
async fn pair(
    app: AppHandle,
    state: State<'_, Mutex<AppState>>,
    relay_url: String,
    code: String,
) -> Result<PairResult, String> {
    validate_relay_url(relay_url.trim())?;
    validate_pairing_code(code.trim())?;
    let relay_url = relay_url.trim().trim_end_matches('/').to_string();
    let hostname = config::get_hostname();
    let os = std::env::consts::OS.to_string();

    let claim_url = format!("{relay_url}/agent/pair/{}/claim", code.trim());
    let client = tls_pinning::get_pinned_http_client();
    let resp = client
        .post(&claim_url)
        .json(&serde_json::json!({ "hostname": hostname, "os": os }))
        .send()
        .await
        .map_err(|e| format!("Network error: {e}"))?;

    if !resp.status().is_success() {
        let status = resp.status();
        let body = resp.text().await.unwrap_or_default();
        return Err(format!("Claim failed ({status}): {body}"));
    }

    let body: serde_json::Value = resp.json().await.map_err(|e| e.to_string())?;
    let token = body["token"].as_str().ok_or("No token in response")?.to_string();
    let agent_machine_id = body["agentMachineId"]
        .as_str()
        .ok_or("No agentMachineId in response")?
        .to_string();

    credentials::store_token(&token).map_err(|e| format!("Failed to store token: {e}"))?;
    if let Some(rt) = body["refreshToken"].as_str() {
        let _ = credentials::store_refresh_token(rt);
    }

    let existing = config::load(&app);
    let new_cfg = config::AgentConfig {
        relay_url: relay_url.clone(),
        token: String::new(),
        agent_machine_id: agent_machine_id.clone(),
        hostname: hostname.clone(),
        relay_url_override: existing.relay_url_override,
        token_issued_at: Some(now_unix()),
    };
    config::save(&app, &new_cfg).map_err(|e| format!("Failed to save config: {e}"))?;
    start_ws_connection(&app, &state, relay_url.clone(), token.clone());

    let link = fetch_phone_link(&relay_url, &token).await;
    Ok(PairResult {
        paired: true,
        relay_url,
        hostname,
        agent_machine_id,
        link_token: link.as_ref().map(|l| l.link_token.clone()).unwrap_or_default(),
        link_code: link.as_ref().map(|l| l.link_code.clone()).unwrap_or_default(),
    })
}

/// Generate a short-lived phone link token for QR display.
/// Uses the stored agent token — no bootstrap secret involved.
#[tauri::command]
async fn get_phone_link(app: AppHandle) -> Result<PhoneLinkResult, String> {
    let cfg = config::load(&app);
    if !cfg.is_paired() {
        return Err("Not paired".into());
    }
    let token = credentials::load_token()
        .map_err(|e| e.to_string())?
        .ok_or_else(|| "No stored token; re-pair required".to_string())?;

    fetch_phone_link(&cfg.relay_url, &token)
        .await
        .ok_or_else(|| "Failed to generate phone link".to_string())
}

/// Internal helper — fetches a fresh phone link from the relay.
async fn fetch_phone_link(relay_url: &str, agent_token: &str) -> Option<PhoneLinkResult> {
    let url = format!("{}/agent/refresh-phone-link", relay_url.trim_end_matches('/'));
    let resp = tls_pinning::get_pinned_http_client()
        .post(&url)
        .header("Authorization", format!("Bearer {agent_token}"))
        .send()
        .await
        .ok()?;

    if !resp.status().is_success() {
        return None;
    }

    let body: serde_json::Value = resp.json().await.ok()?;
    Some(PhoneLinkResult {
        relay_url: relay_url.trim_end_matches('/').to_string(),
        link_token: body["linkToken"].as_str()?.to_string(),
        link_code: body["linkCode"].as_str().unwrap_or("").to_string(),
    })
}

#[tauri::command]
fn unpair(app: AppHandle, state: State<Mutex<AppState>>) {
    stop_ws_connection(&state);
    credentials::delete_all();
    pin_manager::clear_pins();
    config::clear(&app);
}

#[tauri::command]
async fn check_update(app: AppHandle) -> Result<bool, String> {
    use tauri_plugin_updater::UpdaterExt;
    let update = app
        .updater()
        .map_err(|e| e.to_string())?
        .check()
        .await
        .map_err(|e| e.to_string())?;
    Ok(update.is_some())
}

// ── Approval commands ─────────────────────────────────────────────────────────

#[tauri::command]
fn approve_action_id(app: AppHandle, request_id: String) {
    let state = app.state::<Mutex<ApprovalState>>();
    let mut guard = state.lock().unwrap();
    if let Some(tx) = guard.pending.remove(&request_id) {
        let _ = tx.send(true);
    }
}

#[tauri::command]
fn deny_action_id(app: AppHandle, request_id: String) {
    let state = app.state::<Mutex<ApprovalState>>();
    let mut guard = state.lock().unwrap();
    if let Some(tx) = guard.pending.remove(&request_id) {
        let _ = tx.send(false);
    }
}

/// Returns a snapshot of pending approval request IDs so the frontend can
/// re-render after reconnect without missing an in-flight request.
#[tauri::command]
fn get_pending_approvals(app: AppHandle) -> Vec<String> {
    let state = app.state::<Mutex<ApprovalState>>();
    let guard = state.lock().unwrap();
    guard.pending.keys().cloned().collect()
}

// ── WebSocket helpers ─────────────────────────────────────────────────────────

fn start_ws_connection(
    app: &AppHandle,
    state: &State<Mutex<AppState>>,
    relay_url: String,
    token: String,
) {
    let (tx, rx) = watch::channel(false);
    let mut guard = state.lock().unwrap();
    if let Some(old_tx) = guard.ws_stop_tx.take() {
        let _ = old_tx.send(true);
    }
    guard.ws_stop_tx = Some(tx);
    ws_client::spawn(app.clone(), relay_url, token, rx);
}

fn stop_ws_connection(state: &State<Mutex<AppState>>) {
    let mut guard = state.lock().unwrap();
    if let Some(tx) = guard.ws_stop_tx.take() {
        let _ = tx.send(true);
    }
}

// ── Validation ────────────────────────────────────────────────────────────────

fn validate_relay_url(url: &str) -> Result<(), String> {
    if !url.starts_with("https://") {
        return Err("Relay URL must use HTTPS (must start with https://)".to_string());
    }
    Ok(())
}

fn validate_pairing_code(code: &str) -> Result<(), String> {
    let code = code.trim();
    if code.is_empty() {
        return Err("Pairing code is required".to_string());
    }
    if code.len() > 64 || !code.chars().all(|c| c.is_ascii_alphanumeric() || c == '-') {
        return Err("Invalid pairing code format".to_string());
    }
    Ok(())
}

fn now_unix() -> i64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs() as i64)
        .unwrap_or(0)
}

// ── App setup ─────────────────────────────────────────────────────────────────

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_updater::Builder::new().build())
        .plugin(tauri_plugin_process::init())
        .manage(Mutex::new(AppState { ws_stop_tx: None }))
        .manage(Mutex::new(ApprovalState { pending: HashMap::new() }))
        .setup(|app| {
            ws_client::init_claude_path();

            // Fail closed in release builds if the OS credential store is unavailable.
            if let Err(e) = credentials::check_availability() {
                if cfg!(debug_assertions) {
                    eprintln!("[credentials] WARNING: {e} (continuing in debug mode)");
                } else {
                    return Err(format!(
                        "[credentials] {e} — cannot start without secure credential storage"
                    ).into());
                }
            }

            let mut cfg = config::load(app.handle());

            // One-time migration from legacy plaintext token.
            if !cfg.token.is_empty() {
                if credentials::migrate_from_plaintext(&cfg.token) {
                    eprintln!("[credentials] migrated plaintext token to keyring");
                }
                cfg.token = String::new();
                let _ = config::save(app.handle(), &cfg);
            }

            if cfg.is_paired() {
                match credentials::load_token() {
                    Ok(Some(token)) => {
                        let state = app.state::<Mutex<AppState>>();
                        start_ws_connection(app.handle(), &state, cfg.relay_url, token);
                    }
                    Ok(None) => {
                        eprintln!("[credentials] paired config but no token in keyring; re-pair required");
                    }
                    Err(e) => {
                        eprintln!("[credentials] token retrieval failed at startup: {e}");
                    }
                }
            }

            let app_handle = app.handle().clone();
            tauri::async_runtime::spawn(async move {
                check_for_update_silently(app_handle).await;
            });

            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            get_status,
            get_relay_defaults,
            update_relay_url,
            pair_with_code,
            pair,
            get_phone_link,
            unpair,
            check_update,
            approve_action_id,
            deny_action_id,
            get_pending_approvals,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

async fn check_for_update_silently(app: AppHandle) {
    use tauri_plugin_updater::UpdaterExt;
    let Ok(updater) = app.updater() else { return };
    let Ok(Some(update)) = updater.check().await else { return };
    eprintln!("[updater] new version available: {}", update.version);
    let _ = app.emit("update_available", update.version.clone());
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    /// The bootstrap token must never be compiled into the agent binary.
    /// This test fails at compile time (via option_env!) if build.rs injects
    /// VITE_BOOTSTRAP_TOKEN, acting as a CI guard against secret re-introduction.
    #[test]
    fn test_no_bootstrap_token_in_binary() {
        assert!(
            option_env!("VITE_BOOTSTRAP_TOKEN").is_none(),
            "VITE_BOOTSTRAP_TOKEN must not be compiled into the agent binary — \
             see build.rs for the security rationale"
        );
    }

    /// RELAY_URL is not a secret (it is a public endpoint address); baking it
    /// in is intentional. Verify it is present when the build is configured.
    #[test]
    fn test_relay_url_not_treated_as_secret() {
        // Simply confirm the constant exists and is accessible.
        let _ = super::RELAY_URL;
    }

    #[test]
    fn test_validate_pairing_code_rejects_empty() {
        assert!(super::validate_pairing_code("").is_err());
    }

    #[test]
    fn test_validate_pairing_code_rejects_special_chars() {
        assert!(super::validate_pairing_code("ABC; DROP TABLE").is_err());
    }

    #[test]
    fn test_validate_pairing_code_accepts_valid() {
        assert!(super::validate_pairing_code("AABBCCDD1234").is_ok());
        assert!(super::validate_pairing_code("abc-123-xyz").is_ok());
    }

    #[test]
    fn test_validate_relay_url_requires_https() {
        assert!(super::validate_relay_url("http://example.com").is_err());
        assert!(super::validate_relay_url("https://example.com").is_ok());
    }
}
